services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    hostname: localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3,dynamodb,lambda
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - TMPDIR=/var/tmp/localstack
      - PERSISTENCE=1
      - LS_LOG=trace
    volumes:
      - ./data/localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - localstack_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - localstack_network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node-server
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - localstack_network
    depends_on:
      - localstack

networks:
  localstack_network:
    driver: bridge